version: '3.8'

services:
  backend:
    build:
      context: ./example-backend/
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./example-frontend/
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "127.0.0.1:5000:5000"
    command: serve -s -l 5000 build
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
