version: "3.8"

services:
  backend:
    build:
      context: ./example-backend/
    # ports:
    # - "127.0.0.1:8080:8080"
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./example-frontend/
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
    # ports:
    # - "127.0.0.1:5000:5000"
    command: serve -s -l 5000 build
    depends_on:
      - backend

  redis:
    image: redis:7-alpine

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
